name: Run Tests (Windows)

on:
  push

jobs:
  run_tests:
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        include:
          - generator: "Visual Studio 17 2022"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake Project
        working-directory: ${{github.workspace}}
        run: cmake -B build -G "${{ matrix.generator }}" .

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --target run-tests
