name: Run Tests (macOS)

on:
  push

jobs:
  run_tests:
    strategy:
      matrix:
        os: [macos-11, macos-12]
        # macos-13 is currently beta so not included

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake Project
        working-directory: ${{github.workspace}}
        run: cmake -DCMAKE_BUILD_TYPE=Debug -B build -G "Unix Makefiles" .

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --target run-tests -- -j 6

